=== herudo/Scub-foundation-incubator/framework/scub-foundation-incubator-framework-core-implementation/conf/test/resources/database.dtd
<!ELEMENT dataset (
   (NUMBER_VALUE|
    PERSONNE_TYPE)*)>

<!ELEMENT NUMBER_VALUE EMPTY>
<!ATTLIST NUMBER_VALUE
    ID CDATA #REQUIRED
    INT_VALUE CDATA #IMPLIED
    VERSION CDATA #REQUIRED
>

<!ELEMENT PERSONNE_TYPE EMPTY>
<!ATTLIST PERSONNE_TYPE
    ID CDATA #REQUIRED
    LABEL CDATA #REQUIRED
    VERSION CDATA #REQUIRED
>

=== herudo/Scub-foundation-incubator/framework/scub-foundation-incubator-framework-core-implementation/conf/test/resources/datasets/NumberSearchCriterion.dataset.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "../database.dtd">
<dataset>
	<NUMBER_VALUE ID="1" INT_VALUE="0" VERSION="0" />
	<NUMBER_VALUE ID="2" INT_VALUE="1" VERSION="0" />
	<NUMBER_VALUE ID="3" INT_VALUE="2" VERSION="0" />
	<NUMBER_VALUE ID="4" INT_VALUE="3" VERSION="0" />
	<NUMBER_VALUE ID="5" INT_VALUE="5" VERSION="0" />
	<NUMBER_VALUE ID="6" INT_VALUE="6" VERSION="0" />
	<NUMBER_VALUE ID="7" INT_VALUE="10" VERSION="0" />
	<NUMBER_VALUE ID="8" VERSION="0" />
</dataset>
